#include <iostream.h>

int main() {
   int a, b;

   cout << "Vpišite prvo število .... ";
   cin >> a;
   cout << "Vpišite drugo število ... ";
   cin >> b;

   cout << endl;
   cout << a << " + " << b << " = " << a + b << endl;
   cout << a << " - " << b << " = " << a - b << endl;
   cout << a << " * " << b << " = " << a * b << endl;
   cout << a << " / " << b << " = " << a / b << endl;

   return 1;
}
