// A. Znak je predstavljen z enim bajtom, tip int pa jih zaseda veè.
// Èe konkreten raèunalnik zapisuje števila od nižjih naslovov proti
// višjim bo vse delovalo dobro. Èe pa zapisuje ravno obratno, bo
// število napaèno.

// B. Unsigned predstavlja naravna števila, kar kode so. Èe bi uporabili
// int pa bi se lahko zgodilo (ni nujno) da števio napaèno tulmaèi (recimo
// kot negativno).

// C. Podobno kot odgovor A. Spet je odvisno v katero smer zapistje raèunalnik
// bite v spominu.
